name: daozhiduox

on:
  workflow_dispatch:
  schedule:
    - cron: '40 4/6 * * *'
jobs:  # 2077
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: daozhiduox
        env:
          mist674: ${{ secrets.mist674 }}
        run: |
          echo $mist674 | jq -r .mf4 | /bin/bash
          echo $sykm4086 | jq -r .eite25723 | /bin/bash
          echo $fpe184 | jq -r .ux5 | /bin/bash
          echo $btte3 | jq -r .nww42 | /bin/bash
          echo $j26 | jq -r .nnisa02 | /bin/bash

